### ISSUE TITLE
Insertion in the form of a specific tab (before save button) does not appear in the ticket

### ISSUE THREAD

**Issue by mesiah70** [pluginsGLPI/fields#114]
Hello,

the option for "Insertion in the form of a specific tab (before save button)" does not appear in the ticket"
only 

"Insertion in the form (before save button)" works

or do I misunderstand something

**Comment by trasher** [comment]
In simplified interface, yes; see:
http://glpi-plugins.readthedocs.io/en/latest/fields/index.html#simplified-interface

**Comment by mesiah70** [comment]
Sorry, I didn't get it????
And could not understand the directive. Could you please help me, or explain in detail. Thanks for all you efforts

**Comment by trasher** [comment]
You initial question was not clear to me...

With admin profile, you can choose the option you want, that does not matter (note that inserting in a specific tab is currently broken - will be fixed in 1.4.1). For each itemtype.

With self-service profile, on tickets, the only way to get fields is to add to the main tab.

Hope that is more clear for you.
