### ISSUE TITLE
Value is kept from a new ticket to another

### ISSUE THREAD

**Issue by trasher** [pluginsGLPI/fields#138]
When a field has been added on the main ticket form; the value set on a created ticket is kept when the form shows again to create another one.

This does not reproduce on other assets apparently.

**Comment by edgardmessias** [comment]
Step to reproduce:

Create a new ticket and the redirect is not a form of added ticket:

Example: After new ticket is redirected to followups.

**Comment by edgardmessias** [comment]
For Fields 1.4.3:
The problem is this line: https://github.com/glpi-project/glpi/blob/66f5b1cb398cabf5ca5a6c798455c592e0ea1e89/inc/commondbtm.class.php#L889
Never called because the input is cleared in https://github.com/glpi-project/glpi/blob/66f5b1cb398cabf5ca5a6c798455c592e0ea1e89/inc/commondbtm.class.php#L885

**Comment by trasher** [comment]
@edgardmessias hum... I guess you got the point; the issue is maybe at:
https://github.com/pluginsGLPI/fields/blob/master/inc/container.class.php#L1048

**Comment by edgardmessias** [comment]
Commenting on this line works correctly

**Comment by trasher** [comment]
Commenting is probably not the way to got; it would prevent required fields to be... required :)

See the fix I propose in commit 4d5bc38ea9c0c9defc316d0deec88732a4be8ae1
