### ISSUE TITLE
[Injection] Problème de droits lors de la validation d'un modèle d'import avec un champ supplémentaire

### ISSUE THREAD

**Issue by magicbret** [pluginsGLPI/fields#18]
Bonjour,

J'ai ajouté un blocs et 2 champs dans "matériel réseaux". Je crée ensuite un modèle d'import de matériel réseau et j'ai bien mes 2 champs supplémentaires. En revanche, lorsque je valide le modèle d'import, GLPI m'indique que je n'ai pas les droits. Je suis super-admin, entité root, tout est de base.

Il y a t-il une incompatibilité entre les 2 plugins ?

Merci

**Comment by Manu1400** [comment]
Je constate la génération de deux classes d'injection (Injection et InjectionInjection) dans le plugin. #21

Le code d'import peut être donc simplifié au préalable.

Quelle version de GLPI et du plugin utilisez vous ?

**Comment by trasher** [comment]
Hello,

I've just tried with the latest plugin release, I'm not able to reproduce the issue. The value stored in ticket creation is exactly the same that the one I see editing the ticket; carriage return included.

If the issue is not solved on your side, feel free to repoen the ticket, and give more information on how to reproduce.

**Comment by trasher** [comment]
Closing as ne feedback.
