### ISSUE TITLE
Need help - Print tickets with plugin Fields

### ISSUE THREAD

**Issue by phamorais** [pluginsGLPI/fields#281]
Hello guys

I use the fields plugin with GLPI 9.2.3. To print the tickets I use the PDF plugin (https://forge.glpi-project.org/projects/pdf).

However when printing a ticket through the PDF plugin, fields created through the fields plugin are not printed. Is there any possibility of this happening?

**Comment by phamorais** [comment]
@yllen Great! 

We have believe that both plugins are very good and really add value to GLPI. It would be great to have this compatibility, I will wait for a positioning of Fields staff.

**Comment by phamorais** [comment]
Hi Guys,

Is there an intention to implement this improvement?

**Comment by flegastelois** [comment]
Hi @phamorais 

Thank you very much for your feature suggestion.

This issue is now tagged as "enhancement" and is waiting for an external contribution or funding.
If you think you can financially sponsor this feature, you can contact a [GLPI partner](https://glpi-project.org/partners/).

He can directly develop it or contact us for us to do it.

François.

**Comment by phamorais** [comment]
@yllen Hi!

Can u help us?

**Comment by phamorais** [comment]
As there was no response to the request, I will close the issue.

**Comment by Kramito** [comment]
is there a solution to this problem?
