### ISSUE TITLE
when the ticket is closed a wrong valor is displayed

### ISSUE THREAD

**Issue by satyan01** [pluginsGLPI/fields#31]
Hello

I have created fields yes/no, when the ticket is not closed it is ok the field displays No,  but when I close the ticket the valor Yes is diplayed, normally it should be No by default. 

In the database the valor is No

**Comment by ejanakieff** [comment]
Can you fix the problem?

**Comment by trasher** [comment]
I've just tested with the latest plugin release; all seems ok to me:
- add a new tab on ticket with a text field and a yes/no
- solve an existing ticket without changing fields values; the yes/no shows "No"
- change yeas/no to "yes" on another ticket and solve it; the yes/no shows "yes".

I guess the issue has been solved since this issue was reported.
