### ISSUE TITLE
Can't add fields to genericObjects

### ISSUE THREAD

**Issue by tinchonet** [pluginsGLPI/fields#325]
Hi, I'm trying with no success to add a block to a custom object, created with genericObjects plugin.

I really need help with this.

**Comment by tinchonet** [comment]
> 
> 
> Hi, I'm trying with no success to add a block to a custom object, created with genericObjects plugin.
> 
> I really need help with this.

Latest versions.

**Comment by stonebuzz** [comment]
Hi @tinchonet 

actually fields is not compatible with genericobject because 
generiobject plugin does not implement this.

It's a feature request concerning genericobject can you create request to right repo ?

I am closing this issue, feel free to continue the discussion here if you want

Best regards
