### ISSUE TITLE
Incorrect table name

### ISSUE THREAD

**Issue by Neoman** [pluginsGLPI/fields#344]
hi, update install
fields | 1.10.2

Glpi 9.4.4

 Incorrect table name 'glpi_plugin_fields_softwareonesevenoneseventhreezerofourzerothrees'

[2019-11-21 10:00:40] glpisqllog.ERROR: DBmysql::query() in /var/www/html/test/inc/dbmysql.class.php line 188
  *** MySQL query error:
  SQL: CREATE TABLE IF NOT EXISTS `glpi_plugin_fields_softwareonesevenoneseventhreezerofourzerothrees` (
                  `id`                               INT(11)      NOT NULL auto_increment,
                  `items_id`                         INT(11)      NOT NULL,
                  `itemtype`                         VARCHAR(255) DEFAULT 'Software',
                  `plugin_fields_containers_id`      INT(11)      NOT NULL DEFAULT '3',
                  PRIMARY KEY                        (`id`),
                  UNIQUE INDEX `itemtype_item_container`
                     (`itemtype`, `items_id`, `plugin_fields_containers_id`)
               ) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
  Error: Incorrect table name 'glpi_plugin_fields_softwareonesevenoneseventhreezerofourzerothrees'
  Backtrace :
  ...evenoneseventhreezerofourzerothree.class.php:24 
  plugins/fields/setup.php:253                       PluginFieldsSoftwareonesevenoneseventhreezerofourzerothree::install()
  plugins/fields/hook.php:92                         plugin_fields_checkFiles()
  inc/plugin.class.php:521                           plugin_fields_install()
  front/plugin.form.php:47                           Plugin->install()
  {"user":"719@glpi"}

**Comment by stonebuzz** [comment]
Hi @Neoman 

since version 1.9.2, migration process update all containers / fields name containing number to string
to prevent problem with glpi and search form.

Originally you've got a field name containing  '171730403' updated to 'softwareonesevenoneseventhreezerofourzerothrees'
 
When plugin try to migrate table name, mysql answer with error because table name length is more than the limit (64 char).

Can you test this PR
https://github.com/pluginsGLPI/fields/pull/351

PR fix migration for table name with more than 64 char

Best regards

**Comment by cedric-anne** [comment]
Fixed in #351 .
