### ISSUE TITLE
Multiligne non pris en compte sur la création de Ticket

### ISSUE THREAD

**Issue by toniolol** [pluginsGLPI/fields#35]
Bonjour,
Avec un champs Texte (lignes multiples) les \rn ne sont pas pris en compte sur la création d'un Ticket.
Après validation l'affichage est ; _TexteLigne1_**rn**_TexteLigne2_**rn**_TexteLigne3_

Par contre en éditant un Ticket et en enlevant les rn puis en reformatant comme il faut le texte la sauvegarde multiligne se fait bien.

Cordialement

**Comment by toniolol** [comment]
Bonjour,

Avez-vous un retour sur ce bug ?
Pour le moment la seule solution palliative est de lancer un update de la bdd avec un replace du rn par \r.

Cordialement,

**Comment by toniolol** [comment]
Bonjour,

Si je place un trigger en before update pour transformer les rn en \r j'obtiens l'erreur sql suivante : 
Error: Champ 'descriptiondelaproblmatiquefield' inconnu dans field list
Et la valeur passée qui pose souci : "testerntestrntest"

**Comment by trasher** [comment]
Hello,

I've just tried with the latest plugin release, I'm not able to reproduce the issue. The value stored in ticket creation is exactly the same that the one I see editing the ticket; carriage return included.

If the issue is not solved on your side, feel free to repoen the ticket, and give more information on how to reproduce.
