### ISSUE TITLE
Fields Plugin can not be configured as automatic action due to active profile check

### ISSUE THREAD

**Issue by zampat** [pluginsGLPI/fields#428]
The Fields import could be automated with automatic action.
In container.class.php the code makes reference to $_SESSION['glpiactiveprofile']['id'] not set in case of Cron job.

There would the a solution found in other sections of GLPI core:
if (Session::isCron() || !isset($_SESSION['glpiactiveprofile']['id'])) {
     // define a default Session
 }

The code runs in this exception:
*** Uncaught Exception ErrorException: Undefined index: glpiactiveprofile in /usr/share/glpi/plugins/fields/inc/container.class.php at line 1446

**Comment by Mirkk** [comment]
Hello @orthagh , this bug is still on #1604 of container.class.php, since commit https://github.com/pluginsGLPI/fields/commit/99397a466c325b192e927539992ab430efb331be#diff-d98456827cd3db0388884db44e3d5ea5

if $_SESSION['glpiactiveprofile']['id'] is not defined. 

My small workaround in function getAddSearchOptions(), #1604:
         # AND profiles.profiles_id = ".(int) $_SESSION['glpiactiveprofile']['id']."	
	  if (!Session::isCron()){     # || !isset($_SESSION['glpiactiveprofile']['id'])) {  ## (this second part is optional in my case but with it it would be is complete)
              $query .= " AND profiles.profiles_id = ".(int) $_SESSION['glpiactiveprofile']['id'];
          }

Thanks!
best
Mirko

**Comment by cedric-anne** [comment]
@Mirkk 

Could you please open a new PR ?
