### ISSUE TITLE
Searches doesn't work on fields created as number on 1.15.3

### ISSUE THREAD

**Issue by elmotofan** [pluginsGLPI/fields#536]
**Describe the bug**
After migrate from version 1.12.10 to 1.15.3.
When you try to search (ex. Software items), filter by a field created as number, cannot find items.

**To Reproduce**

Go to 'Setup' / 'Additional Fields'
Click on 'Add'
  (create a container for any item type)
Add new Field as Number
Complete on an item this field with any number.
The make a search using filter this field and using "contain" write that number

**Expected behavior**
I expect to view the item found in this search.

Screenshots
![image](https://user-images.githubusercontent.com/57363519/172749597-7fb94e38-56ed-4be4-abd2-e04dcc785f94.png)

![image](https://user-images.githubusercontent.com/57363519/172749710-31580c94-a57d-4a47-9d17-71caa18551c6.png)

But the item exits.

![image](https://user-images.githubusercontent.com/57363519/172750068-d17334d9-e8bc-4d24-a785-47335809028a.png)

Additional Comments
Using Debug mode, I can saw that the SQL Sentence is appended a "." after expression to search:

If I run that sentence on SQL query manager, also have any results. But If I remove the "." can obtain the item that I looking for.

`glpi_plugin_fields_softwaresoftwares_otroreferentefield`.`itemtype` = 'Software' )
WHERE `glpi_softwares`.`is_deleted` = 0 AND `glpi_softwares`.`is_template` = 0 AND ( (`glpi_plugin_fields_softwaresoftwares_idaplicacinfield`.`idaplicacinfield` LIKE '%560.%' ) ) GROUP BY `glpi_softwares`.`id`
ORDER BY `id`

GLPI / Plugins (please complete the following information):

GLPI version 10
list of all plugins with their version (available in GLPI > Setup > General > tab System > bottom of the page)
fields Name: Additional Fields Version: 1.15.3 State: Enabled

thanks in advance!

OS: Ubuntu 20.04 LTS
Browser chrome and safari have the same issues
Version Latest for both.

**Comment by cconard96** [comment]
The issue is that GLPI 10 now has smarter search for decimals (the search data type this plugin uses for all its number fields). The problem is that this plugin uses a basic string type in the database for the field values.
If the plugin had used a decimal column type instead, then the search with the decimal point included would have worked.

See glpi-project/glpi#10417
Previously if you searched "22" in decimal fields, it did not find values equal to "22.5" for example. Now it does by force-adding that decimal point.
