### ISSUE TITLE
SQL Error - missing table ?

### ISSUE THREAD

**Issue by mathieuchateau** [pluginsGLPI/fields#75]
Hello,
GLPI: 0.90.1
plugin 0.90-1.1

After adding some fields, when I try to fill them on computers, nothing happen.
I can see dropdown value I added
Historical tab log the change, but changes is not done.

I see this in sql-error.log:
XXXX = name of tab
Container with id 4 does exist 
I have another tab for user, which does work.

So I removed this one and added another one. It does work.

```
  *** MySQL query error:
  SQL: SELECT *
                FROM `glpi_plugin_fields_computerXXXXs` WHERE plugin_fields_containers_id = 4 AND items_id = 2
  Error: Table 'glpi.glpi_plugin_fields_computerXXXXs' doesn't exist
  Backtrace :
  inc/commondbtm.class.php:255
  plugins/fields/inc/field.class.php:673             CommonDBTM->find()
  plugins/fields/inc/field.class.php:424             PluginFieldsField::prepareHtmlFields()
  plugins/fields/inc/container.class.php:523         PluginFieldsField::showForTabContainer()
  inc/commonglpi.class.php:469                       PluginFieldsContainer::displayTabContentForItem()
  ajax/common.tabs.php:91                            CommonGLPI::displayStandardTab()
```

**Comment by trasher** [comment]
Tha table should have been created along with the new field... So I guess the real issue appears on fields creation ; this is just the result of this initial error.

Could you try to see in your logs if something went wrong when you've created the fields?

Also, several releases have been made since the 0.90-1.1; you may try with a more recent version of the plugin.

**Comment by trasher** [comment]
I close this one since it should have been fixed on a more recent release. Feel free to reopen it this is not fixed.
