### ISSUE TITLE
glpi 10.0.15: after updating fields's plugin to 1.21.10, in plugin datainjection, the mappings is empty

### ISSUE THREAD

**Issue by hcimadomo-procsi** [pluginsGLPI/fields#801]
glpi 10.0.15
Hello,
After updating field plugin to 1.21.10, in plugin datainjection, the mappings is empty. After search in log, i found error in php-error.log.
trace stack is
![image](https://github.com/pluginsGLPI/fields/assets/103555535/18d26b6e-2ba5-445d-83a2-52f97ddc3e4f)
any idea ?
Best regards

**Comment by hcimadomo-procsi** [comment]
hello,
in fact, after uninstall and reinstall plugin field (v1.21.10) and datainjection (v2.13.5), the mapping is now present. But the fields of bloc not appair. for exemple, i have bloc "ordinateur" 
![image](https://github.com/pluginsGLPI/fields/assets/103555535/469f5e89-e818-44fd-92a8-fa4655579778)
and the mapping not show it:
![image](https://github.com/pluginsGLPI/fields/assets/103555535/8e801f67-8673-49db-9030-4c7bb83fb1e6)
After search in php-error.log, i found: 
![image](https://github.com/pluginsGLPI/fields/assets/103555535/bf30e584-faaf-4ba3-a002-61d1d2d0bafc)

help ..
Best regards

**Comment by Juinness** [comment]
I have found a solution. 
When a field object is created, a class is generated in the folder `files/_plugins/fields/inc/`. 
In the static method `get_table($classname = null)` the name of the same class is expected as parameter.

The Datainjection-Plugin calls the method without parameters so an empty string is always returned.

To fix the error, I recommend adapting the template plugins/fields/templates/injection.class.tpl as follows:

FROM
```
static function getTable($classname = null) {
        if ($classname === null) {
            return '';
        }
        $parent_class = get_parent_class($classname);

        if ($parent_class === false) {
            return '';
        }

        return getTableForItemType($parent_class);
}
```

TO
```
static function getTable() {
        $parent_class = get_parent_class($classname);

        if ($parent_class === false) {
            return '';
        }

        return getTableForItemType($parent_class);
}
```

The field object must then be recreated so that the class with the fix is generated.

**Comment by stonebuzz** [comment]
Please test this =)

#807

**Comment by Juinness** [comment]
> Please apply this =)
> 
> #807
> 
> you need to regenerate container after applying fix

Oh, I missed the PR. Use the Solution From @stonebuzz

**Comment by stonebuzz** [comment]
Fixed since https://github.com/pluginsGLPI/fields/releases/tag/1.21.10
