### ISSUE TITLE
Erreur 500 lors de l'appel via webcal

### ISSUE THREAD

**Issue by johannsan** [pluginsGLPI/fields#97]
Bonjour.

Nous obtenons une erreur 500 lors de l’utilisation du webcal.

Got error 'PHP message: PHP Fatal error:  Class 'PluginFieldsContainer' not found in www/helpdesk/plugins/fields/setup.php on line 182.

Après analyse, lors de l'appel du webcal sans être authentifié, la déclaration de la classe PluginFieldsContainer n'est pas faite.

Cela provient de la condition dans le setup.php aux lignes 71-74 : 
   $plugin = new Plugin();
   if ($plugin->isInstalled('fields')
       && $plugin->isActivated('fields')
       && Session::getLoginUserID() ) {
La classe n'est pas déclarée lorsqu'on n'est pas authentifié.

Mais le script cherche à l'instancier ligne 127 : 
 $itemtypes = PluginFieldsContainer::getUsedItemtypes();

Cordialement.
Johann

**Comment by trasher** [comment]
Which version of the plugin are you using? Wcich version of GLPI?

The call to `getUsedItemtypes` is inside the condition in the latest release; so if you are not identified, the initialization is not done.
Also, until you precise the version used; I've no idea what the `plugins/fields/setup.php on line 182` refers to.

**Comment by johannsan** [comment]
Hello,

"The call to getUsedItemtypes is inside the condition in the latest release; so if you are not identified, the initialization is not done." --> you are right

Own version is : 1.3.1

line 182 : "Class 'PluginFieldsContainer' not found" because  the initialization is not done. (not identified)
![image](https://cloud.githubusercontent.com/assets/6028912/21221749/e93edc46-c2be-11e6-995c-1e1cc3f35259.png)

**Comment by trasher** [comment]
OK, thanks for the precisions.

Could you please try the following:
```diff
diff --git a/setup.php b/setup.php
index 0b28ff1..a2c7612 100644
--- a/setup.php
+++ b/setup.php
@@ -200,7 +200,8 @@ function plugin_fields_checkFiles() {
 
    if (isset($_SESSION['glpiactiveentities'])
       && $plugin->isInstalled('fields')
-      && $plugin->isActivated('fields')) {
+      && $plugin->isActivated('fields')
+      && Session::getLoginUserID()) {
 
       Plugin::registerClass('PluginFieldsContainer');
       Plugin::registerClass('PluginFieldsDropdown');
```

**Comment by tsadock** [comment]
Hello, 
The problem is not still resolved. 
When you call the front/planning.php, in the URL, we have the UserId and at line 70, we have   $user->loadMinimalSession(...).
That the reason why, even if you call Session::getLoginUserID(), it will return the User ID, whereas there is no user logged in.

In the version 1.4.3 of your plugin, you just have to add "&& $_SESSION["glpiroot"]" in your conditionnal at line 208 of the setup.php, because this variable is not used in the  loadMinimalSession  method.

This will resolve the bug.

**Comment by Krisstof** [comment]
"Fields" plugin v1.4.3
Same problem with webcal export : no error in Apple Calendar or Thunderbird CalDAV but no syncing, no tasks events.

So I tried to add : 
&& $_SESSION["glpiroot"]
At line 208 of setup.php file (of "fields" plugin directory of course)

Sample :
function plugin_fields_checkFiles() {
   $plugin = new Plugin();

   if (isset($_SESSION['glpiactiveentities'])
      && $plugin->isInstalled('fields')
      && $plugin->isActivated('fields')
      && Session::getLoginUserID()) {
      && $_SESSION["glpiroot"]
      Plugin::registerClass('PluginFieldsContainer');
      Plugin::registerClass('PluginFieldsDropdown');
      Plugin::registerClass('PluginFieldsField');
But when I did that : glpi web interface became blank
So it seems there is a syntax glitch somewhere.

I don't understand why I need to use "Fields" plugin in order to have Planning Webcal Export working ?

**Comment by tsadock** [comment]
Hello,

You don't have to install "Fields" plugin in order to have Planning Webcal Export working.

Simply, if you already use this plugin, it could be the reason why you encounter this error.

You have an error in your code, do as following : 

   if (isset($_SESSION['glpiactiveentities'])
      && $plugin->isInstalled('fields')
      && $plugin->isActivated('fields')
      && Session::getLoginUserID()
      && $_SESSION["glpiroot"]) {

**Comment by Krisstof** [comment]
I apologize because I didn't understand that was perhaps caused by "Fields" plugin.
So with your correct syntax : GLPI Web pages are displaying correctly but planning webcal export still not syncing Tasks.

I deactivate "Fields" Plugins and still no Tasks event on CalDAV.
I discovered that WebCal Export sync really well "Notes" but not "Tasks".
It is annoying because the beauty of "GLPI Planning" was to give us the ability to compare "traditional CalDAV clients Rendez-vous" and real tasks done.

At the end I don't know where to find the problem. Why "Notes" and not "Tasks" ?

Many thanks for your help.

Christophe Ferrandon

**Comment by trasher** [comment]
Commit c42e0afb62abbe4a12e30653e219caac66df5b9c shoudl solve the issue.

**Comment by Krisstof** [comment]
Change done
Still no "ticket task" on WebCal.

Best

**Comment by trasher** [comment]
@Krisstof since it seems you have issues **without** plugin installed; your problem is not the one we're talking about here.

**Comment by Krisstof** [comment]
You are right, the bug is on GLPI 9.1.1
Sorry
